trigger: none

resources:
  repositories:
    - repository: pipelineTemplateRepository
      type: github
      name: emmanuelbenitez/Be.Stateless.Build.Agent.Yaml.Pipeline.Templates
      ref: refs/heads/pipeline-with-multi-outputs
      endpoint: github.com_icraftsoftware

extends:
  template: Pipelines/net/manual-release.yml@pipelineTemplateRepository
  parameters:
    ProjectOrSolutionPath: "$(Build.SourcesDirectory)/Be.Stateless.Dsl.Configuration.sln"
    Major: 2
    Minor: 0